hashing
software-students-fall2021/project-setup-penguin pull request #169
Opened 2021-11-16 03:57 UTC by zhangrmatthew

2021-11-16 15:32 UTC, kdduan submitted a review, later dismissed
LGTM! 🚀

2021-11-16 17:16 UTC, cindykimxp commented
make sure to resolve conflicts and then merge! looks good :)

2021-11-18 23:33 UTC, janethuangg requested changes
as mentioned over slack, check out the GET endpoint to figure out how to incorporate passport auth into this – key changes include 
using `const userId = req.user._id` in the controller file 
and 
adding `passport.authenticate("jwt", { session: false }),` into the route

2021-11-20 20:33 UTC, janethuangg commented on back-end/routes/userRoutes.js
> +  "/:userId",
route should just be `"/"`

2021-11-20 20:33 UTC, janethuangg commented on back-end/routes/userRoutes.js
> +  "/:userId",
route should just be `"/"`

2021-11-20 20:38 UTC, kdduan requested changes
the BE logic looks good - main change is to remove the userId url param from the endpoint since the FE won't have access to the raw userId

2021-11-22 03:33 UTC, closed without merging