fe piece for update and delete user (in progress, don't review yet just don't know how to delete, i'll commit style updates here))
software-students-fall2021/project-setup-penguin pull request #176
Opened 2021-11-17 16:40 UTC by zhangrmatthew

![image](https://user-images.githubusercontent.com/56270011/142242521-107d26bc-dd70-4a76-b54a-936f2535694e.png)

2021-11-20 03:59 UTC, zhangrmatthew commented
![Peek 2021-11-19 22-57](https://user-images.githubusercontent.com/56270011/142713744-895581dd-1f51-40d2-8ed8-9f26f1cf9fa6.gif)
updated styling - pls review

2021-11-20 20:39 UTC, janethuangg requested changes
blocking since 1) can't compile 2) you'll need to implement one more `useEffect` to pull in the existing data (in other words, the user should be able to see the name/email they have on file before updating it) – see https://github.com/software-students-fall2021/project-setup-penguin/blob/1d5743f7346aebf43c56a7051a4ba4ad5a9ca2bc/front-end/src/views/UpdateDeck.jsx#L15 for example

2021-11-20 20:39 UTC, janethuangg commented on front-end/src/views/edit_account/editAccount.jsx
> +      url: `http://localhost:8000/user/${userId}}`,
you don't need to pass in the userId here (in fact – you can't because it does not exist)

2021-11-20 20:39 UTC, janethuangg commented on front-end/src/views/edit_account/editAccount.jsx
> +  const [redirect, setRedirect] = useState(false);
little odd that the initial state is a boolean when it's ultimately going to be a string – just do useState("");

2021-11-20 20:40 UTC, janethuangg commented on front-end/src/views/edit_account/editAccount.jsx
> +      url: `http://localhost:8000/user/${userId}}`,
the urls should just be http://localhost:8000/user assuming you've updated the BEs to reflect that

2021-11-20 20:40 UTC, janethuangg commented on front-end/src/views/edit_account/editAccount.jsx
> +      url: `http://localhost:8000/user/${userId}}`,
(for both PATCH and DELETE)

2021-11-20 20:43 UTC, janethuangg commented on front-end/src/views/edit_account/editAccount.jsx
> +    return <Redirect path={redirect} />;
oh i've also never seen the `path` prop in a `Redirect` component https://v5.reactrouter.com/web/api/Redirect
I would recommend replacing with `to` unless you're using `path` for some special reason

2021-11-20 22:29 UTC, zhangrmatthew commented on front-end/src/views/edit_account/editAccount.jsx
> +      url: `http://localhost:8000/user/${userId}}`,
How do you recommend using useEffect, the get user endpoint doesn't return user metadata right?

2021-11-21 05:09 UTC, kdduan commented on front-end/src/views/edit_account/editAccount.jsx
> +      url: `http://localhost:8000/user/${userId}}`,
Yea the GET user endpoint doesn't have any user metadata. You can probably just create another endpoint that gives back user metadata

2021-11-22 19:17 UTC, janethuangg requested changes
you overwrote some significant stuff from master, so I think the best course of action is to [reset certain files to master](https://stackoverflow.com/questions/37972753/git-reset-single-file-in-feature-branch-to-be-the-same-as-in-master) and then incorporate your changes into those fresh files (specifically userController.js and userRoutes.js)

generally speaking, if you know you didn't change a certain section, choose master's version, not yours

2021-11-22 19:19 UTC, janethuangg commented
another tip – if you just look at the file diff for your PR https://github.com/software-students-fall2021/project-setup-penguin/pull/176/files, you should be able to determine whether the changes made are changes you actually made vs. changes you brought in when resolving merge conflicts

2021-11-22 22:38 UTC, closed without merging