implementing submitting with enter, required field clarity, homepage adjust
software-students-fall2021/project-setup-penguin pull request #220
Opened 2021-12-02 21:47 UTC by jharsch2401

Centering homepage buttons on mobile view (#207), adding required field denotions on signup/login, deck and card create(#205), and making it so login, signup, deck create, deck edit, and account edit can be submitted by clicking enter (#196)

![mobileview](https://user-images.githubusercontent.com/60206755/144508183-447eac94-a51a-4f56-81ee-7d0f53503da0.png)
![login](https://user-images.githubusercontent.com/60206755/144508185-aa2080bb-7ba6-4519-8dd6-8d063ec03105.png)
![cardname](https://user-images.githubusercontent.com/60206755/144508186-0072045c-2d3d-4a89-ada9-42feca9718af.png)
![deck](https://user-images.githubusercontent.com/60206755/144508187-d49b721c-b5d8-4292-845b-443419e4b627.png)

2021-12-03 15:51 UTC, janethuangg requested changes
blocking since your change to DeckEditor has the potential to crash the page, but otherwise, everything looks good! also left a non-blocking suggestion about styling the "denotes required field" text alongside the "Show password" checkbox 

thanks for including screenshots too! super helpful

2021-12-03 15:51 UTC, janethuangg commented on front-end/src/common/account-prompt-modal/SignupOrLogin.jsx
> +      <i>{'* denotes required field'}</i>
wondering if something like this might look better...
![Screen Shot 2021-12-03 at 10 40 04 AM](https://user-images.githubusercontent.com/52385987/144630315-0110041d-0e79-4c06-add7-ffadbfc94dc2.png)

made this directly in browser by moving the "denotes req field" into .SignupOrLogin__showPassword, putting the checkbox and "Show Password" into a div, then applying flex styling to .SignupOrLogin__showPassword

2021-12-03 15:51 UTC, janethuangg commented on front-end/src/common/deck-editor/DeckEditor.jsx
> +      this.form.submit();
I think `this` is undefined here, so probably don't want to use it

I also think the DeckEditor form was working fine (submitting on enter) originally (correct me if I'm wrong), so you might not need to make any changes to it

2021-12-03 15:51 UTC, janethuangg commented on front-end/src/common/account-prompt-modal/SignupOrLogin.jsx
> +        <form>
what happens when the button is not wrapped in the form tags?

2021-12-03 18:23 UTC, jharsch2401 commented on front-end/src/common/account-prompt-modal/SignupOrLogin.jsx
> +      <i>{'* denotes required field'}</i>
This looks better, I like it! Made the change.

2021-12-03 18:23 UTC, jharsch2401 commented on front-end/src/common/account-prompt-modal/SignupOrLogin.jsx
> +        <form>
Oops, that was outdated from when I tried a different approach, I removed this. Thanks for catching!

2021-12-03 18:23 UTC, jharsch2401 commented on front-end/src/common/deck-editor/DeckEditor.jsx
> +      this.form.submit();
You're right it was working, reverted my changes

2021-12-03 20:10 UTC, janethuangg approved these changes
thanks for incorporating fixes & suggestion!

2021-12-03 20:11 UTC, janethuangg commented
hmm might need to resolve merge conflicts first – will reapprove after!

2021-12-04 03:50 UTC, janethuangg requested changes
one small but very important change must be made! otherwise lgtm :)

2021-12-04 03:50 UTC, janethuangg commented on front-end/src/views/account_page/AccountPage.jsx
> +        setUserCards(response.data);
so much cleaner!!

2021-12-04 03:50 UTC, janethuangg commented on front-end/src/views/account_page/AccountPage.jsx
>        ownedContent.push(pageElement);
i think this needs to be `joinedContent`!

2021-12-04 16:50 UTC, jharsch2401 commented on front-end/src/views/account_page/AccountPage.jsx
>        ownedContent.push(pageElement);
OMG great catch thank you!! Just fixed

2021-12-04 17:16 UTC, janethuangg approved these changes
lgtm!

2021-12-04 17:17 UTC, merged